version: '3.7'

services:

  db:
    container_name: db
    image: postgres:13.0
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    networks:
      - backend
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data

  tgbot:
    container_name: tgbot
    build:
      context: ./app
    command: python app.py
    volumes:
      - ./$SSL_DIR$SSL_CERT:/app/$SSL_DIR$SSL_CERT:ro
      - ./$SSL_DIR$SSL_PRIV:/app/$SSL_DIR$SSL_PRIV:ro
    env_file:
      - .env
    ports:
      - $WEBHOOK_PORT:$WEBAPP_PORT
    networks:
      - backend
    restart: always
    depends_on:
      - db

networks:
  backend:
